const mongoose=require('mongoose');
const candidateHistorySchema=mongoose.Schema({
    userId:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'User',
        required:true
    },
    domain:{
        type:String,
        required:true
    },
    description:{
        type:String,
        required:true
    },
    analysis:{
        type:String,
        required:true
    },
    atsScore:{
        type:Number,
        required:true
    },
    createdAt:{
        type:Date,
        default:Date.now
    }
},
{
    timestamps:true
})
module.exports=mongoose.model('candidateHistory',candidateHistorySchema)